## Numpy Assignment
Student Name:

## Instructions:
- Please complete the questions below.
- for each cell, complete it with good essays and code examples
- Please comment your code indicating how you approached the problem

# What is NumPy, and what are some of its key features?


In [24]:
# to install numpy when you have python installed.

#conda install numpy or 

#pip install numpy

# How do you create a NumPy array using Python's built-in range() function?


In [ ]:
import numpy as np  # Ensure numpy is imported

# Create a NumPy array using range()
array_from_range = np.array(list(range(10)))  # Creates an array with values from 0 to 9
print(array_from_range)  # Output the array


# What is the difference between a scalar value and a vector in NumPy?
with code example

A scalar value in NumPy is a single numerical value, while a vector is a one-dimensional array of numbers.
# Scalars can be thought of as 0-dimensional arrays, whereas vectors are 1-dimensional arrays.


In [1]:

# Example of a scalar
scalar_value = np.array(5)  # This is a scalar
print("Scalar value:", scalar_value)

# Example of a vector
vector_value = np.array([1, 2, 3, 4, 5])  # This is a vector
print("Vector value:", vector_value)


NameError: name 'np' is not defined

# How do you calculate the mean of a NumPy array using the mean() function?

Examples 





#



1. Import the NumPy library.
2. Create or define a NumPy array.
3. Use the `.mean()` function to calculate the mean of the array.

In [8]:

# Example 
import numpy as np

array = np.array([1, 2, 3, 4, 5])

mean_value = array.mean()

print("Mean of the array:", mean_value)

Mean of the array: 3.0


# What is broadcasting in NumPy, and how can it be useful?


Broadcasting in NumPy is a feature that allows operations on arrays of different shapes. When performing operations, NumPy automatically expands the smaller array to match the shape of the larger array without creating unnecessary copies of data. 


This is useful for efficient computation and simplifies code when working with arrays of varying dimensions.

# How can you slice a NumPy array to extract a subarray?





1. Use slicing syntax `[start:stop:step]` to extract a subarray.
2. Apply slicing on rows, columns, or both for multidimensional arrays.




In [9]:
import numpy as np

# Example NumPy array
array = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

# Extract a subarray ( first two rows and first two columns)
subarray = array[:2, :2]

print("Original array:")
print(array)
print("Subarray:")
print(subarray)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Subarray:
[[1 2]
 [4 5]]


# What are some of the available functions for performing element-wise operations on NumPy arrays?





1. **Arithmetic Operations**: `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()`.
2. **Mathematical Functions**: `np.sqrt()`, `np.exp()`, `np.log()`, `np.sin()`, `np.cos()`.
3. **Comparison Operations**: `np.equal()`, `np.greater()`, `np.less()`.
4. **Logical Operations**: `np.logical_and()`, `np.logical_or()`, `np.logical_not()`.



# How do you reshape a NumPy array to have a different shape?






1. Use the `.reshape()` method or `np.reshape()` function.
2. Ensure the new shape is compatible with the total number of elements in the array.




In [10]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to 2 rows and 3 columns
reshaped_array = array.reshape(2, 3)

print("Original array:")
print(array)
print("Reshaped array:")
print(reshaped_array)

Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]


# How do you perform matrix multiplication on two NumPy arrays using the dot() function?



1. Import the NumPy library.
2. Define two NumPy arrays representing matrices.
3. Use the `np.dot()` function or the `.dot()` method to perform matrix multiplication.




In [15]:
import numpy as np

# Define two matrices
matrix_a = np.array([[1, 2], 
                     [3, 4]])
matrix_b = np.array([[5, 6], 
                     [7, 8]])

# matrix multiplication
result = np.dot(matrix_a, matrix_b)

print("Matrix A:")
print(matrix_a)
print("Matrix B:")
print(matrix_b)
print("Result of matrix multiplication:")
print(result)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Result of matrix multiplication:
[[19 22]
 [43 50]]


# How can you use the where() function to apply a condition to a NumPy array?



1. Use `np.where(condition, x, y)` to apply a condition.
2. Replace elements in the array based on the condition:
   - If the condition is `True`, use value `x`.
   - If the condition is `False`, use value `y`.

### Example:


In [16]:
import numpy as np

#  NumPy array
array = np.array([10, 20, 30, 40, 50])

#  condition: Replace values greater than 25 with 1, others with 0
result = np.where(array > 25, 1, 0)

print("Original array:")
print(array)
print("Result after applying np.where:")
print(result)

Original array:
[10 20 30 40 50]
Result after applying np.where:
[0 0 1 1 1]


# What is the difference between the flatten() and ravel() functions in NumPy?






1. **`flatten()`**:
   - Creates a new one-dimensional array from the original array.
   - Changes made to this new array won’t affect the original array.

2. **`ravel()`**:
   - Produces a one-dimensional view of the original array, if possible.
   - If it’s a view, changes to this array will also change the original array.



# How do you use NumPy's advanced indexing capabilities to select specific elements from an array?




### Example:


In [17]:
import numpy as np

# NumPy array
array = np.array([10, 20, 30, 40, 50])

# Select specific elements using an array of indices
indices = [0, 2, 4]
selected_elements = array[indices]

# Select elements using a boolean mask
mask = array > 25
masked_elements = array[mask]

print("Original array:")
print(array)
print("Selected elements using indices:")
print(selected_elements)
print("Selected elements using boolean mask:")
print(masked_elements)

Original array:
[10 20 30 40 50]
Selected elements using indices:
[10 30 50]
Selected elements using boolean mask:
[30 40 50]


# How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?


Broadcasting lets you perform operations on arrays with different shapes by automatically expanding the smaller array to match the larger one. This makes calculations easier without needing to manually resize arrays.

Example:


In [18]:
import numpy as np

# Example arrays
array_a = np.array([[1, 2, 3], 
                    [4, 5, 6]])  # 2x3 array
array_b = np.array([10, 20, 30])  # 1x3 array

# Add the arrays (broadcasting happens automatically)
result = array_a + array_b

print("Result:")
print(result)

Result:
[[11 22 33]
 [14 25 36]]


### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [19]:
import numpy as np

# Prompt user for input
user_input = input("Enter a list of numbers separated by commas: ")

# Convert input string to NumPy array
numbers = np.array([float(num) for num in user_input.split(",")])

# Calculate 
mean = np.mean(numbers)
median = np.median(numbers)
std_dev = np.std(numbers)
maximum = np.max(numbers)
minimum = np.min(numbers)

# Display Results
print("Results for the input array:")
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")
print(f"Maximum: {maximum}")
print(f"Minimum: {minimum}")

Results for the input array:
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Maximum: 5.0
Minimum: 1.0
